name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-

      - name: Lint
        run: |
          yarn --frozen-lockfile
          yarn lint

      - name: Install, Test and Build [APP]
        run: |
          yarn --frozen-lockfile
          yarn test.ci
          yarn build

      - name: Install, Test and Build [SERVER]
        run: |
          yarn --frozen-lockfile
          yarn test.server.ci
          yarn build.server
        env:
          CI: true
